name: Test workflow
run-name: example workflow run
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: run echo
        run: echo "build"
      
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: run test
        run: echo "test"
  job-3:
      runs-on: ubuntu-latest
      steps:
        - name: run test
          run: echo "test"
